### ISSUE TITLE
Strong Delay and camera selection

### ISSUE THREAD

**Issue by AlanBlack2003** [zhongyi-zhou/GestureIMT#1]
I have the following two problems while testing the project with a Philips SPC 1330NC, Intel RealSense and AzureKinect. The graphics card is a RTX 2080 Ti and the CPU Intel Xeon with 3.1GHz.:

1.the frame rate of the camera is always 5-10 fps, which in itself would not be so bad. However, when I point my hand into the camera, a few minutes pass until I see my hand in the GUI. So it is a very strong delay. Do I have a buffer somewhere or is the problem somewhere else? 
 
2.the project always seems to detect the first camera. Is there a way to select the camera yourself? Because it doesn't work for me or the mask of the object recognition doesn't work correctly when I rewrite the code.

In the file GestureIMT/tree/main/demo_app/public/assets/js/webrtc.js in line 23 your code looks like this : document.getElementById("webcam").srcObject = e.streams[0];
 
If I change it to the following, the mask doesn't work anymore but I can select the camera itself: 
const stream = await navigator.mediaDevices.getUserMedia(constraints);
window.stream = stream; document.getElementById("webcam").srcObject = stream;

This is one of many examples I have tried.

I would appreciate any help especially for the first problem and thank you.

**Comment by zhongyi-zhou** [comment]
Thanks for using our system!

> 1.the frame rate of the camera is always 5-10 fps, which in itself would not be so bad. However, when I point my hand into the camera, a few minutes pass until I see my hand in the GUI. So it is a very strong delay. Do I have a buffer somewhere or is the problem somewhere else?

I think the main issue probably is that the computation is slower than normal.

While you are running the code, can you check the GPU utility and the CPU utility in real time by using the following command in another cmd?
```
htop
```
```
watch -n 1 nvidia-smi
```
Maybe you can take a screen recording and reply to me?

Also, you can try changing the default fps range in the front end [here](https://github.com/zhongyi-zhou/GestureIMT/blob/290f5445b4be72f53f08ed696b99c417954f3000/demo_app/public/assets/js/webrtc/webrtc.js#L110-L121) into:

```javascript
        var constraints = {
            video: {
                width: 640,
                height: 480, 
                frameRate: {
                    min: 1,  // very important to define min value here
                    ideal: 5,
                    max: 10,
                },
            },
            audio: false
        };
```


> 2.the project always seems to detect the first camera. Is there a way to select the camera yourself? Because it doesn't work for me or the mask of the object recognition doesn't work correctly when I rewrite the code.

What browser you are using? I think in chrome you can choose the camera you want to use in the web. 
See details in this youtube tutorial:
https://www.youtube.com/watch?v=w1eLpbEKeKc

**Comment by AlanBlack2003** [comment]
Thank you in advance for the quick feedback and help. 

1
Attached are two videos, the first "first.mkv" is how it looks with the problem (frameRate: {min: 20, ideal: 24, max: 25,}). 
The second video "second.mkv" after your proposed solution to the problem (frameRate: {min: 1, ideal: 4, max: 5,}. 
Is in any case a little better now. And you can test better with it now
[recording.zip](https://github.com/zhongyi-zhou/GestureIMT/files/10861413/recording.zip)

2
I also used chrome for this, however it does not take the default camera which is in the settings. 
Small Senario: Webapp starts with webcam, although in chrome the default camera is the Realsense. When I put the webcam out of the usb slot and refresh the webpage, the realsense is recognized. Now when I put the webcam back in the usb slot and refresh the website, the webcam is detected again. Although the whole time the realsense is set as default.

**Comment by zhongyi-zhou** [comment]
> Is in any case a little better now. And you can test better with it now

Do you mean it works now?

Note that since your camera has relatively low fps, if you change the setting to (frameRate: {min: 1, ideal: 4, max: 5,}, it should run with low accumulated latency, but the fps would still be low.

> Small Senario: Webapp starts with webcam, although in chrome the default camera is the Realsense. When I put the webcam out of the usb slot and refresh the webpage, the realsense is recognized. Now when I put the webcam back in the usb slot and refresh the website, the webcam is detected again. Although the whole time the realsense is set as default.

I cannot fully understand this part. Which camera is the one you want to use: realsense or webcam?

**Comment by AlanBlack2003** [comment]
> Do you mean it works now?

Yes, it's enough for testing for now.


> I cannot fully understand this part. Which camera is the one you want to use: realsense or webcam?

I want to use the camera which are set as default in the Chrome settings. However, it always takes the webcam automatically and I can't change that. Unless the webcam is not connected to the computer.

**Comment by zhongyi-zhou** [comment]
> I want to use the camera which are set as default in the Chrome settings. However, it always takes the webcam automatically and I can't change that. Unless the webcam is not connected to the computer.

I remember when I tested the system, I could switch between two cameras just by using the chrome setting.
I do not have another external camera at hand. I will double-check next week when I go to the lab, and reply to you whether the issue also occurs on my side.

**Comment by zhongyi-zhou** [comment]
I have tested it on my side, and I can fluently switch between two cameras.

Here is what I did in chrome:
first, click on the camera icon here 
![7FRK~PV`X7O_X_DDLRS5O`1](https://user-images.githubusercontent.com/33302970/223713565-b1eb44b5-3c2d-43d4-8c28-753b0e9970f5.png)
and then choose your target camera here:
![6MV` V}9WK3CH~U$BRG0TE2](https://user-images.githubusercontent.com/33302970/223713941-4dfcc745-8320-404a-8388-257948013a3c.png)

If it still does not work, could you double-check with other web applications to see whether it is a hardware issue?
